### ISSUE TITLE
Rolls and spells

### ISSUE THREAD

**Issue by Rhopper85** [Ratismal/blargbot#30]
I am somewhat new to making my own bot and I only need a few features for my discord bot for personal use. I want to incorporate your spells and rolls but unsure how to do that. I was curious if you could give me some guidance?

**Comment by Ratismal** [comment]
As blargbot is open-source, the files you would want to look into are
https://github.com/Ratismal/blargbot/blob/master/dcommands/roll.js
https://github.com/Ratismal/blargbot/blob/master/dcommands/spell.js

I have no plans to offer lessons on how to add these features. I'd highly recommend you first learn to program, and then think of a way to implement it yourself.
