### ISSUE TITLE
Restrict access to certain chat channels?

### ISSUE THREAD

**Issue by Altilla** [Ratismal/blargbot#31]
Let's say for instance I didn't want Blargbot in #General-Chat but I wanted it in some other channel.

Can this be added

**Comment by Ratismal** [comment]
Use the blacklist command.
```
b!blacklist #channel
```
This restricts usage by disabling the bot in the specified channel. Keep in mind that staff (owners, administrators, and those specified by permoverrides) will be able to use the bot in blacklisted channels, but nobody else will.

Please let me know if this answers your question.

**Comment by Altilla** [comment]
Appreciate the support

**Comment by Ratismal** [comment]
Glad to hear it!
